export enum ContentReportReason {
  OBJECTIONABLE_CONTENT = 'OBJECTIONABLE_CONTENT',
  HARASSMENT = 'HARASSMENT',
  HATE_SPEECH = 'HATE_SPEECH',
  SEXUAL_CONTENT = 'SEXUAL_CONTENT',
  SPAM = 'SPAM',
  VIOLENCE = 'VIOLENCE',
  SCAM = 'SCAM',
  OTHER = 'OTHER',
}
