export enum FraudType {
  FAKE_PRODUCT = 'FAKE_PRODUCT',
  PAYMENT_FRAUD = 'PAYMENT_FRAUD',
  NO_DELIVERY = 'NO_DELIVERY',
  COUNTERFEIT = 'COUNTERFEIT',
  MISREPRESENTATION = 'MISREPRESENTATION',
  SCAM = 'SCAM',
  OTHER = 'OTHER',
}
