export enum MessageType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  SYSTEM = 'SYSTEM',
  SAFE_PAYMENT_INITIATED = 'SAFE_PAYMENT_INITIATED',
  SAFE_PAYMENT_VERIFIED = 'SAFE_PAYMENT_VERIFIED',
  PAYMENT_TRANSFERRED = 'PAYMENT_TRANSFERRED',
  DIRECT_TRADE_REQUEST = 'DIRECT_TRADE_REQUEST',
  LOCATION_SHARING_STARTED = 'LOCATION_SHARING_STARTED',
  LOCATION_SHARING_STOPPED = 'LOCATION_SHARING_STOPPED',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
}
