export enum PointSourceType {
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  SUGGESTION_REWARD = 'SUGGESTION_REWARD',
  ADMIN_GRANT = 'ADMIN_GRANT',
  REFERRAL_BONUS = 'REFERRAL_BONUS',
  WITHDRAWAL = 'WITHDRAWAL',
}
