export enum PointSourceType {
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  SUGGESTION_REWARD = 'SUGGESTION_REWARD',
  ADMIN_GRANT = 'ADMIN_GRANT',
  REFERRAL_BONUS = 'REFERRAL_BONUS',
  WITHDRAWAL = 'WITHDRAWAL',
  REGISTRATION_BONUS = 'REGISTRATION_BONUS',
  PHONE_VERIFIED_BONUS = 'PHONE_VERIFIED_BONUS',
  EMAIL_VERIFIED_BONUS = 'EMAIL_VERIFIED_BONUS',
  KBZPAY_VERIFIED_BONUS = 'KBZPAY_VERIFIED_BONUS',
  FACEBOOK_FOLLOW_REWARD = 'FACEBOOK_FOLLOW_REWARD',
}
