export enum TransactionStatus {
  INITIATED = 'INITIATED',
  SAFE_PAYMENT_PENDING = 'SAFE_PAYMENT_PENDING',
  SAFE_PAYMENT_RECEIVED = 'SAFE_PAYMENT_RECEIVED',
  BUYER_COMPLETED = 'BUYER_COMPLETED',
  SELLER_COMPLETED = 'SELLER_COMPLETED',
  COMPLETED = 'COMPLETED',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}
