-- AlterEnum
ALTER TYPE "MessageType" ADD VALUE 'DIRECT_TRADE_LOCATION_ACCEPTED';
ALTER TYPE "MessageType" ADD VALUE 'DIRECT_TRADE_LOCATION_CHANGE_REQUESTED';
ALTER TYPE "MessageType" ADD VALUE 'DIRECT_TRADE_LOCATION_CHANGE_ACCEPTED';
ALTER TYPE "MessageType" ADD VALUE 'DIRECT_TRADE_LOCATION_CHANGE_DENIED';
