name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 47.82.249.130
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/admin/flexusedmarket/flexUsedItemSellingAppBe
            git pull origin main
            npm ci
            npx prisma generate
            npm run build
            npx prisma migrate deploy
            sudo systemctl restart flex-used-market-be.service
            sudo systemctl status flex-used-market-be.service --no-pager
